CREATE TABLE IF NOT EXISTS trades.opportunities
(
    id                  UUID DEFAULT generateUUIDv4(),
    created_at          DateTime DEFAULT now(),
    trade_mode          String,
    asset               String,
    strategy            String,
    signal_time         DateTime,
    nifty_spot          Float64 DEFAULT 0,
    vix                 Float64 DEFAULT 0,
    vix_regime          String DEFAULT '',
    pcr                 Float64 DEFAULT 0,
    market_trend        String DEFAULT '',
    fii_stance          String DEFAULT '',
    day_of_week         String DEFAULT '',
    is_event_day        UInt8 DEFAULT 0,
    event_name          String DEFAULT '',
    expiry              Date,
    strike_call         Float64 DEFAULT 0,
    strike_put          Float64 DEFAULT 0,
    premium_call        Float64 DEFAULT 0,
    premium_put         Float64 DEFAULT 0,
    total_premium       Float64 DEFAULT 0,
    lot_size            UInt16 DEFAULT 25,
    lots                UInt8 DEFAULT 1,
    gross_premium       Float64 DEFAULT 0,
    margin_required     Float64 DEFAULT 0,
    breakeven_upper     Float64 DEFAULT 0,
    breakeven_lower     Float64 DEFAULT 0,
    range_width_pct     Float64 DEFAULT 0,
    probability_profit  Float64 DEFAULT 0,
    delta_call          Float64 DEFAULT 0,
    delta_put           Float64 DEFAULT 0,
    iv_rank             Float64 DEFAULT 0,
    confidence_score    UInt8 DEFAULT 0,
    target_pct          Float64 DEFAULT 50,
    stop_loss_pct       Float64 DEFAULT 200,
    target_premium      Float64 DEFAULT 0,
    stop_loss_premium   Float64 DEFAULT 0,
    decision            String DEFAULT '',
    decision_by         String DEFAULT '',
    skip_reason         String DEFAULT '',
    status              String DEFAULT 'open',
    entry_time          Nullable(DateTime),
    entry_nifty         Float64 DEFAULT 0,
    exit_time           Nullable(DateTime),
    exit_reason         String DEFAULT '',
    exit_nifty          Float64 DEFAULT 0,
    exit_premium_call   Float64 DEFAULT 0,
    exit_premium_put    Float64 DEFAULT 0,
    exit_total_premium  Float64 DEFAULT 0,
    pnl_points          Float64 DEFAULT 0,
    pnl_rupees          Float64 DEFAULT 0,
    pnl_pct             Float64 DEFAULT 0,
    profit_captured     Float64 DEFAULT 0,
    was_successful      UInt8 DEFAULT 0,
    agent_notes         String DEFAULT '',
    user_notes          String DEFAULT ''
)
ENGINE = MergeTree()
ORDER BY (trade_mode, signal_time)